package com.yurc.customerbus.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BUS_LINE.
 */
public class BusLine {

    private Long id;
    private String StartTime;
    private String EndTime;
    private String linename;
    private String nearlySite;
    private String distance;
    private String directionStie;

    public BusLine() {
    }

    public BusLine(Long id) {
        this.id = id;
    }

    public BusLine(Long id, String StartTime, String EndTime, String linename, String nearlySite, String distance, String directionStie) {
        this.id = id;
        this.StartTime = StartTime;
        this.EndTime = EndTime;
        this.linename = linename;
        this.nearlySite = nearlySite;
        this.distance = distance;
        this.directionStie = directionStie;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStartTime() {
        return StartTime;
    }

    public void setStartTime(String StartTime) {
        this.StartTime = StartTime;
    }

    public String getEndTime() {
        return EndTime;
    }

    public void setEndTime(String EndTime) {
        this.EndTime = EndTime;
    }

    public String getLinename() {
        return linename;
    }

    public void setLinename(String linename) {
        this.linename = linename;
    }

    public String getNearlySite() {
        return nearlySite;
    }

    public void setNearlySite(String nearlySite) {
        this.nearlySite = nearlySite;
    }

    public String getDistance() {
        return distance;
    }

    public void setDistance(String distance) {
        this.distance = distance;
    }

    public String getDirectionStie() {
        return directionStie;
    }

    public void setDirectionStie(String directionStie) {
        this.directionStie = directionStie;
    }

}
