package com.yurc.customerbus.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yurc.customerbus.dao.BusLineDetailDB;

import com.yurc.customerbus.dao.BusLineDetailDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig busLineDetailDBDaoConfig;

    private final BusLineDetailDBDao busLineDetailDBDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        busLineDetailDBDaoConfig = daoConfigMap.get(BusLineDetailDBDao.class).clone();
        busLineDetailDBDaoConfig.initIdentityScope(type);

        busLineDetailDBDao = new BusLineDetailDBDao(busLineDetailDBDaoConfig, this);

        registerDao(BusLineDetailDB.class, busLineDetailDBDao);
    }
    
    public void clear() {
        busLineDetailDBDaoConfig.getIdentityScope().clear();
    }

    public BusLineDetailDBDao getBusLineDetailDBDao() {
        return busLineDetailDBDao;
    }

}
